{% set name = "cexprtk" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cexprtk-{{ version }}.tar.gz
  sha256: 73b41707ea17ce446f7a23e936b5bf1d8f2932da59c7f46d0e924c544edf63f0

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython
  run:
    - python

test:
  imports:
    - cexprtk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mjdrushton/cexprtk
  license: CPL-1.0
  license_family: OTHER
  license_file: LICENSE
  summary: Mathematical Expression Parsing and Evaluation in Python
  description: |
    cexprtk is a cython wrapper around "C++ Mathematical Expression
    Toolkit Library (ExprTk)". Using cexprtk a powerful mathematical
    expression engine can be incorporated into your python project.
  doc_url: https://github.com/mjdrushton/cexprtk
  dev_url: https://github.com/mjdrushton/cexprtk

extra:
  recipe-maintainers:
    - jan-janssen
